version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  # Maintain dependencies for Python
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    groups:
      python-packages:
        patterns:
          - "*"