on:
  workflow_dispatch:
    inputs:
      sc-ref:
        required: false
        type: string
        description: which siliconcompiler ref to use
      lambdapdk-ref:
        required: false
        type: string
        description: which lambdapdk ref to use
      concurrency:
        required: false
        type: number
        default: 50
        description: how many concurrent runners to use
      runall:
        required: false
        type: boolean
        default: false
        description: run all possible designs to check for possible regression improvements

name: 'Run Gallery Designs'

jobs:
  designs:
    uses: ./.github/workflows/run-designs.yml
    with:
      sc-ref: ${{ inputs.sc-ref }}
      lambdapdk-ref: ${{ inputs.lambdapdk-ref }}
      concurrency: ${{ fromJson(inputs.concurrency) }}
      scgallery-ref: ${{ github.ref }}
      fail-fast: false
      runall: ${{ inputs.runall }}
    secrets: inherit

  update_montage:
    name: Merge image artifacts
    runs-on: ubuntu-latest
    if: always() && !failure() && !cancelled()
    needs: designs

    steps:
      - name: Generate montage
        uses: ./.github/workflows/montage.yml
